version: '3.3'

services:
  scraper:    
    container_name: scraper
    image: scraper
    build: .
    volumes:
      - .:/src
    networks:
      - main_network

  redis:
    container_name: scraper_redis
    image: redis
    ports:
        - "6379"
    networks:
        - main_network

networks:
  main_network:
    driver: bridge
